{
 "title": "Spark Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM loaded classes",
   "type": "stat",
   "description": "Общее количество классов, которые были загружены с момента начала выполнения JVM",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_classes_loaded_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM threads current",
   "type": "gauge",
   "description": "Текущее количество потоков виртуальной машины JVM",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU available",
   "type": "stat",
   "description": "Количество доступных ядер CPU",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM heap memory bytes max",
   "type": "gauge",
   "description": "Максимальное количество (байт) области памяти HEAP JVM",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "bargauge",
   "description": "Количество сборок мусора JVM",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_garbagecollector_collectioncount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory bytes commited",
   "type": "timeseries",
   "description": "Зафиксировано (байты) области памяти HEAP JVM",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_bytes_committed", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "JVM memory bytes used",
   "type": "timeseries",
   "description": "Используемые байты заданной области памяти JVM",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "description": "Время, затраченное на сборку мусора JVM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "DAG Scheduler all jobs",
   "type": "barchart",
   "description": "Количество джобов распределенных планировщиком DAG Scheduler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\".+_driver_dagscheduler_job_alljobs_number\"}",
     "legendFormat": "jobs number"
    }
   ]
  },
  {
   "title": "JVM memory pool allocated bytes",
   "type": "timeseries",
   "description": "Общее количество байт, выделенных в данном пуле памяти JVM. Обновляется только после GC, не непрерывно",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_allocated_bytes_total",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory pool bytes commited",
   "type": "timeseries",
   "description": "Зафиксированные байты пула памяти JVM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}