{
 "title": "Spark Measure Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobName", "label": "job-name", "query": { "query": "label_values(bytesread,job)" } }
  ]
 },
 "panels": [
  {
   "title": "Read bytes",
   "type": "stat",
   "description": "Общее количество прочитанных байт",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bytesread{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Written bytes",
   "type": "stat",
   "description": "Общее количество записанных байт",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "byteswritten{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk spilled bytes",
   "type": "stat",
   "description": "Количество байт на диске, выделенных(spilled) этой задачей",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskbytesspilled{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elapsed time",
   "type": "stat",
   "description": "Время выполнения джобы",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "elapsedtime{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executor cpu time",
   "type": "stat",
   "description": "Процессорное время, затраченное исполнителем на выполнение этой задачи. Сюда входит время выборки данных в случайном порядке(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executorcputime{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor deserialize cpu time",
   "type": "stat",
   "description": "Процессорное время, затраченное исполнителем на десериализацию этой задачи",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executordeserializecputime{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stages number",
   "type": "stat",
   "description": "Количество этапов",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "numstages{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasks number",
   "type": "stat",
   "description": "Количество задач",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "numtasks{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory spilled bytes",
   "type": "stat",
   "description": "Количество байт в памяти, выделенных(spilled) этой задачей",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memorybytesspilled{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Execution Memory",
   "type": "stat",
   "description": "Пиковая память, используемая внутренними структурами данных, созданными во время перетасовок, агрегаций и объединений. Значение этого накопителя должно быть приблизительно равно сумме пиковых размеров всех таких структур данных, созданных в этой задаче. Для заданий SQL это отслеживает только все небезопасные операторы и ExternalSort",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peakexecutionmemory{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor deserialize time",
   "type": "stat",
   "description": "Время, затраченное исполнителем на десериализацию этой задачи",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executordeserializetime{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor run time",
   "type": "stat",
   "description": "Время, затраченное исполнителем на выполнение этой задачи. Сюда входит время выборки данных в случайном порядке(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executorruntime{job='$jobName'}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Read records",
   "type": "stat",
   "description": "Общее количество прочитанных записей",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recordsread{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Written records",
   "type": "stat",
   "description": "Общее количество записанных записей",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recordswritten{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Result serialization time",
   "type": "stat",
   "description": "Количество времени, затраченного на сериализацию результата задачи",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resultserializationtime{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "stat",
   "description": "Количество времени, затраченного виртуальной машиной JVM на сборку мусора при выполнении этой задачи",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvmgctime{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stage duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stageduration{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Result size",
   "type": "stat",
   "description": "Количество байт, переданных этой задачей обратно драйверу в качестве результата задачи",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "resultsize{job='$jobName'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shuffle total blocks fetched",
   "type": "stat",
   "description": "Количество блоков, извлеченных в ходе операций перетасовки (как локальных, так и удаленных)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shuffletotalblocksfetched{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle total bytes read",
   "type": "stat",
   "description": "Количество байт, считанных при операциях перемешивания (как локальных, так и удаленных)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shuffletotalbytesread{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle local blocks fetched",
   "type": "stat",
   "description": "Количество локальных блоков (в отличие от считанных с удаленного исполнителя), извлеченных в ходе операций перетасовки(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflelocalblocksfetched{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle local bytes read",
   "type": "stat",
   "description": "Количество байт, считываемых при операциях перетасовки с локального диска (в отличие от считывания с удаленного исполнителя)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflelocalbytesread{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle records read",
   "type": "stat",
   "description": "Количество записей, считанных при операциях перетасовки(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflerecordsread{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle bytes written",
   "type": "stat",
   "description": "Количество байт, записанных при операциях перетасовки(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflebyteswritten{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle fetch wait time",
   "type": "stat",
   "description": "Время, затраченное задачей на ожидание удаленных блоков в случайном порядке. Сюда входит только время блокировки входных данных в случайном порядке. Например, если блок B извлекается, в то время как задача все еще не завершила обработку блока A, это не считается блокировкой в блоке B",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflefetchwaittime{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle records written",
   "type": "stat",
   "description": "Количество записей, записанных в ходе операций перетасовки(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflerecordswritten{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle remote blocks fetched",
   "type": "stat",
   "description": "Количество удаленных блоков, извлеченных в ходе операций перетасовки(shuffle)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shuffleremoteblocksfetched{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle remote bytes read",
   "type": "stat",
   "description": "Количество удаленных байт, считанных при операциях перемешивания",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shuffleremotebytesread{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle remote bytes read to disk",
   "type": "stat",
   "description": "Количество удаленных байт, считываемых на диск при операциях случайного чтения. Большие блоки извлекаются на диск при операциях случайного чтения, в отличие от считывания в память, что является поведением по умолчанию",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shuffleremotebytesreadtodisk{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle write time",
   "type": "stat",
   "description": "Время, затрачиваемое на блокировку записи в дисковый или буферный кэш",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shufflewritetime{job='$jobName'}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}